### PR TITLE
Changes To Run Ch3. Data Load Notebook End-To-End

### PR DESCRIPTION
**Pull request by PrestonBlackburn**
Some idempotency updates to allow for chapter_3_data_load.ipynb to be ran end-to-end multiple times:
- Added loading credentials from .config file for convenience
- Switched "CREATE OR REPLACE" to "CREATE .... IF NOT EXISTS" in some places
- Truncated tables if they existed before loading
- Added "overwrite" option when saving tables where applicable
- Used existing "@MY_IMAGES" stage for the last UDF, so you don't need a separate internal stage + data for the last couple cells

*also - requirements should probably be specified somewhere (pillow dependency is referenced in data load notebook)

### CODE REVIEW

**Comment by sgsshankar** [comment]
@viveksrinivasanss Can you please review the changes and approve?

**Comment by PrestonBlackburn** [comment]
I just added the commits for the other two notebooks as well. Now all of the chapter 3 notebooks are reviewed/tested

Notes on the other two notebooks:
- In some cases the snowpark dataframe outputs were hard to read, so I paired down the tables
- A couple cases where the code didn't run, and I made fixes (for example neededing to overwrite the marketing table)
- Pretty much nothing was changed in the agg analysis notebook

**Comment by PrestonBlackburn** [comment]
Added commits for chapter 4 notebook. No major changes, just:
- Added session db and schema to context
- Had to add an option to overwrite tables to prevent error (even on first run)

**Comment by sgsshankar** [comment]
@PrestonBlackburn Can you please give separate PR for each Chapter? Its easier for us to merge it that way since we have to update the code.

**Comment by sgsshankar** [comment]
Closing this PR. Will use individual PR for each Chapter.

**Comment by PrestonBlackburn** [comment]
Sounds good. I just split them out and opened new PRs for the chapters

**Comment by PrestonBlackburn** [comment]
@sgsshankar Also, none of these initial drafts of the notebooks have been able to run end-to-end. Going forward can you make these notebooks a little more self-contained, so there are no dependencies between notebooks? 
For the connection parameters, I think they should always come from either a config file or env variables instead of having placeholder text. That makes it a lot easier to re-run the whole notebook for testing purposes (see PRs for example).

**Pull request closed without merging**
